In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

In [4]:
x,y=make_classification(n_samples=100, n_features=2, n_classes=2, random_state=42,n_redundant=0)

In [5]:
x.shape

(100, 2)

In [6]:
y

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [12]:
# custom dataset
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self,features, labels):
        self.features = features
        self.labels = labels
    def __len__(self):
        return len(self.features)
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [13]:
dataset = CustomDataset(x,y)
dataset[0]

(array([0.55942643, 2.38869353]), np.int64(0))

In [14]:
len(dataset)

100

dataloader 

In [17]:
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)
for batch_features, batch_labels in dataloader:
    print(batch_features, batch_labels)
    

tensor([[-2.0583, -2.5234],
        [-0.5083,  1.4805],
        [ 0.0685, -1.7360],
        [-1.0983, -0.8602],
        [ 1.0397, -0.9217],
        [ 1.8399,  2.3045],
        [-2.0035, -2.3996],
        [ 1.3554,  1.1551],
        [ 1.5331,  1.7415],
        [-1.1776, -1.2059]], dtype=torch.float64) tensor([0, 0, 1, 0, 1, 1, 0, 1, 1, 0])
tensor([[-0.7828,  1.2085],
        [ 0.5594,  2.3887],
        [-0.5677,  1.3899],
        [-0.8080,  1.1966],
        [-0.8168, -0.6796],
        [-0.3857,  0.0172],
        [-0.5750, -0.3751],
        [ 0.3273,  0.6245],
        [-1.6483,  0.4177],
        [ 0.2506,  0.1398]], dtype=torch.float64) tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 1])
tensor([[-1.8204,  0.2600],
        [ 0.4506, -1.5008],
        [ 1.2801,  1.2894],
        [-1.4074, -1.5683],
        [-1.4118, -1.5333],
        [ 0.8258,  0.5348],
        [-2.0263,  0.0619],
        [-1.2857,  0.7302],
        [-0.9428,  1.1001],
        [ 1.2799,  1.2590]], dtype=torch.float64) tensor([0, 1, 1,