In [1]:
import torch 
import torch.nn as nn
import torch.optim as optim
import numpy as np 
from collections import Counter 
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk 

In [2]:
document="""Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction 
between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, 
and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, 
and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval."""

In [3]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /Users/imac/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/imac/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

tokenize 

In [4]:
tokens = word_tokenize(document.lower())
print(tokens)

['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'subfield', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on', 'the', 'interaction', 'between', 'computers', 'and', 'humans', 'through', 'natural', 'language', '.', 'the', 'ultimate', 'goal', 'of', 'nlp', 'is', 'to', 'enable', 'computers', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', 'in', 'a', 'valuable', 'way', '.', 'nlp', 'combines', 'computational', 'linguistics', 'with', 'machine', 'learning', ',', 'deep', 'learning', ',', 'statistical', 'modeling', ',', 'and', 'more', '.', 'it', 'has', 'a', 'wide', 'range', 'of', 'applications', 'including', 'language', 'translation', ',', 'sentiment', 'analysis', ',', 'chatbots', ',', 'and', 'information', 'retrieval', '.']


In [5]:
build vocabs 

SyntaxError: invalid syntax (804148952.py, line 1)

In [5]:
Counter(tokens).keys

<function Counter.keys>

build vocab 

In [6]:
vocab={'<UNK>':0}
vocab

{'<UNK>': 0}

In [7]:
for token in Counter(tokens).keys():
    print(token)

natural
language
processing
(
nlp
)
is
a
subfield
of
artificial
intelligence
that
focuses
on
the
interaction
between
computers
and
humans
through
.
ultimate
goal
to
enable
understand
,
interpret
generate
human
in
valuable
way
combines
computational
linguistics
with
machine
learning
deep
statistical
modeling
more
it
has
wide
range
applications
including
translation
sentiment
analysis
chatbots
information
retrieval


In [8]:
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]=len(vocab)

In [9]:
len(vocab)

58

extract sentences from data 

In [10]:
input_sentences =document.split('\n')
input_sentences

['Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction ',
 'between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, ',
 'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, ',
 'and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval.']

In [11]:
input_sentences[2]

'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, '

In [12]:
def text_to_indices(sentence, vocab):
    numerical_sentence=[]
    for token in word_tokenize(sentence):
        numerical_sentence.append(vocab.get(token, vocab['<UNK>']))
    return numerical_sentence

In [13]:
input_numerical_sentence=[]
for sentence in input_sentences:
    input_numerical_sentence.append(text_to_indices(sentence.lower(), vocab))

In [14]:
input_numerical_sentence

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
 [18,
  19,
  20,
  21,
  22,
  1,
  2,
  23,
  16,
  24,
  25,
  10,
  5,
  7,
  26,
  27,
  19,
  26,
  28,
  29,
  30,
  29],
 [20,
  31,
  32,
  2,
  33,
  8,
  34,
  35,
  23,
  5,
  36,
  37,
  38,
  39,
  40,
  41,
  29,
  42,
  41,
  29,
  43,
  44,
  29],
 [20,
  45,
  23,
  46,
  47,
  8,
  48,
  49,
  10,
  50,
  51,
  2,
  52,
  29,
  53,
  54,
  29,
  55,
  29,
  20,
  56,
  57,
  23]]

In [15]:
training_sequence=[]

for sentence in input_numerical_sentence:
    for i in range(1, len(sentence)):
        training_sequence.append(sentence[:i+1])

In [16]:
print(training_sequence)

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], [18, 19], [18, 19, 20], [18, 19, 20, 21], [18, 19, 20, 21, 22], [18, 19, 20, 21, 22, 1], [18, 19, 20, 21, 22, 1, 2], [18, 19, 20, 21, 22, 1, 2, 23], [18, 19, 20, 21, 22, 1, 2, 23, 16], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10, 5], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10, 5, 7], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10, 5, 7, 

In [17]:
len_list=[]

for sequence in training_sequence:
   len_list.append(len(sequence))

In [18]:
len_list

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

In [19]:
max(len_list)

23

In [20]:
[0] * (max(len_list) - len(sequence))

[]

In [21]:
training_sequence[0]

[1, 2]

In [22]:
padded_training_sequence=[]
for sequence in training_sequence:
    padded_training_sequence.append([0]*(max(len_list)-len(sequence))+sequence)


In [23]:
len(padded_training_sequence[0])

23

In [24]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [25]:
padded_training_sequence

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8,

In [26]:
padded_training_sequence[3]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5]

convert into tensor 

In [27]:
padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)
padded_training_sequence

tensor([[ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        [ 0,  0,  0,  ...,  2,  3,  4],
        ...,
        [ 0,  0, 20,  ..., 29, 20, 56],
        [ 0, 20, 45,  ..., 20, 56, 57],
        [20, 45, 23,  ..., 56, 57, 23]])

In [28]:
padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)
padded_training_sequence

/var/folders/79/qf4s258d1979pqm6v_z63bmc0000gn/T/ipykernel_2404/472878272.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)


tensor([[ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        [ 0,  0,  0,  ...,  2,  3,  4],
        ...,
        [ 0,  0, 20,  ..., 29, 20, 56],
        [ 0, 20, 45,  ..., 20, 56, 57],
        [20, 45, 23,  ..., 56, 57, 23]])

In [29]:
X=padded_training_sequence[:,:-1]
y=padded_training_sequence[:,-1]

In [30]:
X

tensor([[ 0,  0,  0,  ...,  0,  0,  1],
        [ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        ...,
        [ 0,  0, 20,  ..., 55, 29, 20],
        [ 0, 20, 45,  ..., 29, 20, 56],
        [20, 45, 23,  ..., 20, 56, 57]])

In [31]:
y

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20,
        21, 22,  1,  2, 23, 16, 24, 25, 10,  5,  7, 26, 27, 19, 26, 28, 29, 30,
        29, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37, 38, 39, 40, 41, 29, 42,
        41, 29, 43, 44, 29, 45, 23, 46, 47,  8, 48, 49, 10, 50, 51,  2, 52, 29,
        53, 54, 29, 55, 29, 20, 56, 57, 23])

In [32]:
len(y)

81

In [33]:
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X=X
        self.y=y
    
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [34]:
dataset=CustomDataset(X,y)
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [35]:
len(dataset)

81

In [36]:
dataloader=DataLoader(dataset, batch_size=32, shuffle=True)
dataloader

In [37]:
for input,output in dataloader:
    print(input)
    print(output)
    

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0, 20, 45, 23, 46, 47,  8, 48, 49, 10, 50,
         51,  2, 52, 29],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          1,  2,  3,  4],
        [ 0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
         12, 13, 14, 15],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0, 18, 19, 20],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 45, 23, 46, 47,  8, 48, 49, 10,
         50, 51,  2, 52],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0, 18, 19],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 45,
         23, 46, 47,  8],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 19, 20, 21, 22,  1,  2, 23,
         16, 24, 25, 10],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 19, 20,
         21, 22,  1,  2],
        [ 0,  0,  0,  0,  0,  0,  0, 

In [38]:
X.shape

torch.Size([81, 22])

In [39]:
len(dataset)

81

In [40]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

LSTM cell 

In [41]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(LSTMModel, self).__init__()
        self.embedding=nn.Embedding(vocab_size, embedding_dim)
        self.lstm=nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc=nn.Linear(hidden_dim, vocab_size)
    
    def forward(self,x):
        x=self.embedding(x)
        output,(h_n,c_n)=self.lstm(x)
        output=self.fc(output[:,-1,:])
        return output

In [42]:
model=LSTMModel(vocab_size=len(vocab), embedding_dim=50, hidden_dim=100)
model

LSTMModel(
  (embedding): Embedding(58, 50)
  (lstm): LSTM(50, 100, batch_first=True)
  (fc): Linear(in_features=100, out_features=58, bias=True)
)

In [43]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [44]:
model.to(device)

LSTMModel(
  (embedding): Embedding(58, 50)
  (lstm): LSTM(50, 100, batch_first=True)
  (fc): Linear(in_features=100, out_features=58, bias=True)
)

In [45]:
print(len(vocab))

58


In [46]:
X=nn.Embedding(284,100)
y=nn.LSTM(100,128,batch_first=True)
z=nn.Linear(128,284)

In [47]:
dataset[0][0].shape

torch.Size([22])

In [48]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 22])

In [49]:
a=dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [50]:
X(a)

tensor([[[-0.8969, -0.3349, -0.1163,  ..., -0.6340, -1.8762, -1.1845],
         [-0.8969, -0.3349, -0.1163,  ..., -0.6340, -1.8762, -1.1845],
         [-0.8969, -0.3349, -0.1163,  ..., -0.6340, -1.8762, -1.1845],
         ...,
         [-0.8969, -0.3349, -0.1163,  ..., -0.6340, -1.8762, -1.1845],
         [-0.8969, -0.3349, -0.1163,  ..., -0.6340, -1.8762, -1.1845],
         [-0.8546,  2.4102, -0.7732,  ...,  0.3870,  1.2290,  1.2507]]],
       grad_fn=<EmbeddingBackward0>)

In [51]:
X(a).shape

torch.Size([1, 22, 100])

In [52]:
b=y(X(a))
b[0].shape

torch.Size([1, 22, 128])

In [53]:
c, d = b
c.shape, d[0].shape, d[1].shape

(torch.Size([1, 22, 128]), torch.Size([1, 1, 128]), torch.Size([1, 1, 128]))

In [54]:
len(d)

2

In [55]:
e, f=d

In [56]:
e.shape

torch.Size([1, 1, 128])

In [57]:
f.shape

torch.Size([1, 1, 128])

In [58]:
f_temp= f.squeeze(0).shape

In [59]:
f_temp=f.squeeze(0)

In [60]:
z(f_temp)

tensor([[ 1.1376e-01,  4.9209e-03,  4.3686e-02, -9.0225e-02, -3.9258e-01,
         -8.2010e-02, -1.1369e-01,  2.0029e-01, -1.1624e-01, -8.1723e-02,
          4.3472e-01,  6.1004e-02, -1.0344e-01,  2.3518e-02,  2.3130e-01,
          2.5214e-02, -3.1325e-01,  2.7854e-01, -2.9860e-01, -2.6012e-02,
         -1.8537e-01,  2.8604e-01, -1.7456e-01, -4.6789e-03, -5.2878e-02,
         -2.0109e-01,  1.2285e-01, -2.1861e-01,  4.7515e-02, -3.2292e-02,
          4.9776e-02,  9.1237e-03, -1.9922e-01, -8.8154e-02, -8.1837e-02,
         -1.5991e-01,  1.0969e-01,  2.8042e-01,  2.6666e-01,  1.8173e-01,
         -2.1545e-01,  7.2407e-02, -3.1198e-01, -2.7406e-01,  2.5875e-01,
          1.0559e-01, -8.8801e-03,  4.5944e-02, -3.1520e-01,  3.3580e-02,
          4.7242e-02,  3.7003e-01,  3.6171e-01,  2.0766e-01,  2.9411e-01,
          2.5737e-01,  6.6494e-02, -1.5750e-01, -5.8758e-04, -2.0996e-01,
          1.1718e-01,  8.2475e-02,  2.3297e-01, -9.7644e-04, -2.6209e-01,
         -8.5118e-02, -5.9250e-02,  3.

In [61]:
(f_temp)

tensor([[ 0.1250, -0.2463, -0.1803,  0.7412, -0.1449, -0.2208, -0.1108, -0.0743,
         -0.2172, -0.0820,  0.2728, -0.3827,  0.0433,  0.3346,  0.1958, -0.0084,
         -0.1186,  0.3244,  0.3154,  0.3635,  0.1891, -0.2465, -0.5597,  0.1358,
         -0.0838,  0.0989,  0.3695,  0.1190, -0.0225, -0.3777,  0.2575, -0.0291,
          0.5799, -0.5103,  0.1456,  0.3096,  0.5449,  0.0538, -0.2381,  0.0204,
         -0.8630,  0.3205, -0.0904,  0.3739,  0.5076, -0.0340,  0.0953, -0.0742,
         -0.1592, -0.4253,  0.0966,  0.2489,  0.4334, -0.1403, -0.4034, -0.2790,
         -0.0615, -0.1500,  0.3986, -0.0064,  0.1228,  0.1822,  0.0169,  0.4087,
         -0.0220, -0.1563,  0.4612,  0.1669, -0.2529, -0.4798,  0.3757, -0.4487,
         -0.4807, -0.5063,  0.6135, -0.1065, -0.6303, -0.3059,  0.5992,  0.1655,
          0.0868,  0.0585, -0.0746, -0.4592,  0.0821,  0.4943,  0.3363, -0.4423,
          0.6923,  0.4320, -0.3460, -0.0488,  0.0737,  0.2680, -0.3654,  0.0234,
         -0.0092, -0.0635, -

In [62]:
f_temp = f.squeeze(0)
len(f_temp[0])

128

In [63]:
len(vocab)

58

training loop 

In [65]:
for batch_x ,batch_y in dataloader:
    print(batch_x, batch_y)
    
    break

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,
          4,  5,  6,  7],
        [20, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37, 38, 39, 40, 41, 29, 42,
         41, 29, 43, 44],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0, 18, 19, 20],
        [ 0,  0, 20, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37, 38, 39, 40, 41,
         29, 42, 41, 29],
        [ 0,  0,  0,  0,  0,  0, 20, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37,
         38, 39, 40, 41],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 45, 23, 46, 47,  8,
         48, 49, 10, 50],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,
          9, 10, 11, 12],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 19, 20, 21, 22,  1,
          2, 23, 16, 24],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0, 20, 45],
        [ 0,  0,  0,  0,  0,  0,  0, 

In [66]:
for params in model.parameters():
    print(params.shape)

torch.Size([58, 50])
torch.Size([400, 50])
torch.Size([400, 100])
torch.Size([400])
torch.Size([400])
torch.Size([58, 100])
torch.Size([58])


In [67]:
epochs=10
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(), lr=0.001)
learn_rate=0.001


In [68]:
for epoch in range(epochs):
    total_loss=0
    for batch_x ,batch_y in dataloader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        optimizer.step()
        total_loss+=loss.item()
    print(f'Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(dataloader)}')

Epoch 1/10, Loss: 4.077004591623942
Epoch 2/10, Loss: 4.029676755269368
Epoch 3/10, Loss: 3.986265023549398
Epoch 4/10, Loss: 3.937494913736979
Epoch 5/10, Loss: 3.8983660538991294
Epoch 6/10, Loss: 3.8487983544667563
Epoch 7/10, Loss: 3.7929464975992837
Epoch 8/10, Loss: 3.733003298441569
Epoch 9/10, Loss: 3.666731278101603
Epoch 10/10, Loss: 3.5715883572896323


prediction 

In [69]:
document.split('\n')

['Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction ',
 'between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, ',
 'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, ',
 'and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval.']

In [70]:
def prediction(model,vocab,text):
    tokenized_text=word_tokenize(text.lower())
    print(tokenized_text)
    
    
    #numerical indices 
    numerical_text=[vocab.get(token, vocab['<UNK>']) for token in tokenized_text]
    print(numerical_text)
    
    
    # padding 
    padded_numerical_text=torch.tensor([0]*(max(len_list)-len(numerical_text))+numerical_text,dtype=torch.long)
    print(padded_numerical_text)
    print(len(padded_numerical_text))
    
    input_tensor=padded_numerical_text.unsqueeze(0).to(device)
    print(input_tensor.shape)
    
    with torch.no_grad():
        output=model(input_tensor)
    predicted_index=torch.argmax(output, dim=1).item()
    index_to_word={idx: word for word, idx in vocab.items()}
    
    print("models output",output)
    print("predicted token index",predicted_index)
    print(len(output))
    print(vocab.keys())
    return text+" "+index_to_word[predicted_index]
  

In [71]:
prediction(model,vocab,"the last train journey")



['the', 'last', 'train', 'journey']
[16, 0, 0, 0]
tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 16,  0,  0,  0])
23
torch.Size([1, 23])
models output tensor([[-0.2043, -0.1463,  1.2782,  0.6113,  0.2725,  0.2382,  0.1744, -0.2497,
          0.4553, -0.2030, -0.1615, -0.6382, -0.7566,  0.1653, -0.3854, -0.3364,
         -0.0375, -0.2496, -0.2552,  0.5774,  0.5364, -0.0605, -0.2505,  0.5728,
         -0.1332, -0.1243, -0.0559, -0.4191, -0.4006, -0.2650, -0.1836,  0.8967,
          0.2962, -0.1285, -0.2235, -0.1214,  0.0793, -0.3989, -0.4833, -0.2108,
         -0.5354, -0.2309, -0.0107, -0.3170, -0.5552,  0.8621,  0.0435, -0.0371,
         -0.1684,  0.4541, -0.0076, -0.3135, -0.1890, -0.4976,  0.0506, -0.4125,
          0.0067,  0.0597]])
predicted token index 2
1
dict_keys(['<UNK>', 'natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'subfield', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on', 'the', 'interaction', 'b

'the last train journey language'

In [72]:
document.split('\n')

['Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction ',
 'between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, ',
 'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, ',
 'and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval.']

In [73]:
import time

In [74]:
num_tokens = 10 
input_text='Daniel checked the last train journey'
for i in range(num_tokens):
    #print(i)
    output_text=prediction(model,vocab,input_text)
    print(output_text)
    input_text=output_text
    time.sleep(0.5)

['daniel', 'checked', 'the', 'last', 'train', 'journey']
[0, 0, 16, 0, 0, 0]
tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 16,  0,  0,  0])
23
torch.Size([1, 23])
models output tensor([[-0.2043, -0.1463,  1.2782,  0.6113,  0.2725,  0.2382,  0.1744, -0.2497,
          0.4553, -0.2030, -0.1615, -0.6382, -0.7566,  0.1653, -0.3854, -0.3364,
         -0.0375, -0.2496, -0.2552,  0.5774,  0.5364, -0.0605, -0.2505,  0.5728,
         -0.1332, -0.1243, -0.0559, -0.4191, -0.4006, -0.2650, -0.1836,  0.8967,
          0.2962, -0.1285, -0.2235, -0.1214,  0.0793, -0.3989, -0.4833, -0.2108,
         -0.5354, -0.2309, -0.0107, -0.3170, -0.5552,  0.8621,  0.0435, -0.0371,
         -0.1684,  0.4541, -0.0076, -0.3135, -0.1890, -0.4976,  0.0506, -0.4125,
          0.0067,  0.0597]])
predicted token index 2
1
dict_keys(['<UNK>', 'natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'subfield', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on

In [75]:
def calculate_accuracy(model,dataloader,device):
    model.eval()
    
    correct=0
    total=0 
    with torch.no_grad():
        for batch_x ,batch_y in dataloader: 
            #print(batch_x, batch_y)
            batch_x ,batch_y=batch_x.to(device),batch_y.to(device)
            output=model(batch_x)
            
            ##print(len(output))
            
            _,predicted=torch.max(output, dim=1)
            print(predicted)
            
            #compare with actual labels 
            
            print(batch_y)
            
            #print(predicted==batch_y)
            correct+=(predicted==batch_y).sum().item()
            total+=batch_y.size(0)
    accuracy=correct/total
    print(f'Accuracy: {accuracy*100:.2f}%')

In [77]:
calculate_accuracy(model,dataloader,device)

tensor([ 2, 29, 23, 41, 23,  2,  2, 29, 29, 28, 16,  7, 29, 15, 29, 29,  2,  2,
         8, 29,  2, 29,  2,  8,  2, 29, 23, 29,  7, 29, 17, 29])
tensor([47, 29, 16, 41, 12, 23, 19, 57, 54, 28, 16, 11, 56, 15, 29, 29,  5, 21,
        49, 55, 20, 20, 45,  8,  2, 39, 23, 42, 27, 29, 17, 53])
tensor([23, 26,  2, 37,  2, 23,  5,  2, 10, 23, 29, 41,  5, 23, 23, 51, 29,  9,
         2,  2,  2,  2, 10,  5, 29, 10,  7, 29,  2, 29,  8, 14])
tensor([ 1, 26, 32, 37, 31, 52, 36, 22, 25, 13, 29, 41, 50, 23, 35, 51, 43,  9,
        33, 46,  3,  4,  2,  5, 29, 10,  7, 29,  2, 44,  8, 14])
tensor([10, 29,  8, 23, 10, 23, 23, 29,  7,  5,  8,  2, 38, 29,  7, 23, 23])
tensor([10, 30, 34, 48, 10, 23, 24, 29, 26,  5,  8,  2, 38, 40,  7,  6, 19])
Accuracy: 44.44%
