In [1]:
import torch 
import torch.nn as nn
import torch.optim as optim
import numpy as np 
from collections import Counter 
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk 

In [9]:
document="""Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction 
between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, 
and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, 
and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval."""

In [10]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /Users/imac/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/imac/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

tokenize 

In [11]:
tokens = word_tokenize(document.lower())
print(tokens)

['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'subfield', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on', 'the', 'interaction', 'between', 'computers', 'and', 'humans', 'through', 'natural', 'language', '.', 'the', 'ultimate', 'goal', 'of', 'nlp', 'is', 'to', 'enable', 'computers', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', 'in', 'a', 'valuable', 'way', '.', 'nlp', 'combines', 'computational', 'linguistics', 'with', 'machine', 'learning', ',', 'deep', 'learning', ',', 'statistical', 'modeling', ',', 'and', 'more', '.', 'it', 'has', 'a', 'wide', 'range', 'of', 'applications', 'including', 'language', 'translation', ',', 'sentiment', 'analysis', ',', 'chatbots', ',', 'and', 'information', 'retrieval', '.']


In [5]:
build vocabs 

SyntaxError: invalid syntax (804148952.py, line 1)

In [12]:
Counter(tokens).keys

<function Counter.keys>

build vocab 

In [13]:
vocab={'<UNK>':0}
vocab

{'<UNK>': 0}

In [14]:
for token in Counter(tokens).keys():
    print(token)

natural
language
processing
(
nlp
)
is
a
subfield
of
artificial
intelligence
that
focuses
on
the
interaction
between
computers
and
humans
through
.
ultimate
goal
to
enable
understand
,
interpret
generate
human
in
valuable
way
combines
computational
linguistics
with
machine
learning
deep
statistical
modeling
more
it
has
wide
range
applications
including
translation
sentiment
analysis
chatbots
information
retrieval


In [15]:
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]=len(vocab)

In [16]:
len(vocab)

58

extract sentences from data 

In [17]:
input_sentences =document.split('\n')
input_sentences

['Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction ',
 'between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, ',
 'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, ',
 'and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval.']

In [18]:
input_sentences[2]

'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, '

In [19]:
def text_to_indices(sentence, vocab):
    numerical_sentence=[]
    for token in word_tokenize(sentence):
        numerical_sentence.append(vocab.get(token, vocab['<UNK>']))
    return numerical_sentence

In [20]:
input_numerical_sentence=[]
for sentence in input_sentences:
    input_numerical_sentence.append(text_to_indices(sentence.lower(), vocab))

In [21]:
input_numerical_sentence

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
 [18,
  19,
  20,
  21,
  22,
  1,
  2,
  23,
  16,
  24,
  25,
  10,
  5,
  7,
  26,
  27,
  19,
  26,
  28,
  29,
  30,
  29],
 [20,
  31,
  32,
  2,
  33,
  8,
  34,
  35,
  23,
  5,
  36,
  37,
  38,
  39,
  40,
  41,
  29,
  42,
  41,
  29,
  43,
  44,
  29],
 [20,
  45,
  23,
  46,
  47,
  8,
  48,
  49,
  10,
  50,
  51,
  2,
  52,
  29,
  53,
  54,
  29,
  55,
  29,
  20,
  56,
  57,
  23]]

In [22]:
training_sequence=[]

for sentence in input_numerical_sentence:
    for i in range(1, len(sentence)):
        training_sequence.append(sentence[:i+1])

In [23]:
print(training_sequence)

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], [18, 19], [18, 19, 20], [18, 19, 20, 21], [18, 19, 20, 21, 22], [18, 19, 20, 21, 22, 1], [18, 19, 20, 21, 22, 1, 2], [18, 19, 20, 21, 22, 1, 2, 23], [18, 19, 20, 21, 22, 1, 2, 23, 16], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10, 5], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10, 5, 7], [18, 19, 20, 21, 22, 1, 2, 23, 16, 24, 25, 10, 5, 7, 

In [24]:
len_list=[]

for sequence in training_sequence:
   len_list.append(len(sequence))

In [25]:
len_list

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

In [26]:
max(len_list)

23

In [27]:
[0] * (max(len_list) - len(sequence))

[]

In [28]:
training_sequence[0]

[1, 2]

In [29]:
padded_training_sequence=[]
for sequence in training_sequence:
    padded_training_sequence.append([0]*(max(len_list)-len(sequence))+sequence)


In [30]:
len(padded_training_sequence[0])

23

In [31]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [32]:
padded_training_sequence

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8,

In [33]:
padded_training_sequence[3]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5]

convert into tensor 

In [34]:
padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)
padded_training_sequence

tensor([[ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        [ 0,  0,  0,  ...,  2,  3,  4],
        ...,
        [ 0,  0, 20,  ..., 29, 20, 56],
        [ 0, 20, 45,  ..., 20, 56, 57],
        [20, 45, 23,  ..., 56, 57, 23]])

In [35]:
padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)
padded_training_sequence

/var/folders/79/qf4s258d1979pqm6v_z63bmc0000gn/T/ipykernel_6828/472878272.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)


tensor([[ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        [ 0,  0,  0,  ...,  2,  3,  4],
        ...,
        [ 0,  0, 20,  ..., 29, 20, 56],
        [ 0, 20, 45,  ..., 20, 56, 57],
        [20, 45, 23,  ..., 56, 57, 23]])

In [38]:
X=padded_training_sequence[:,:-1]
y=padded_training_sequence[:,-1]

In [40]:
X

tensor([[ 0,  0,  0,  ...,  0,  0,  1],
        [ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        ...,
        [ 0,  0, 20,  ..., 55, 29, 20],
        [ 0, 20, 45,  ..., 29, 20, 56],
        [20, 45, 23,  ..., 20, 56, 57]])

In [39]:
y

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20,
        21, 22,  1,  2, 23, 16, 24, 25, 10,  5,  7, 26, 27, 19, 26, 28, 29, 30,
        29, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37, 38, 39, 40, 41, 29, 42,
        41, 29, 43, 44, 29, 45, 23, 46, 47,  8, 48, 49, 10, 50, 51,  2, 52, 29,
        53, 54, 29, 55, 29, 20, 56, 57, 23])

In [41]:
len(y)

81

In [42]:
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X=X
        self.y=y
    
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [43]:
dataset=CustomDataset(X,y)
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [44]:
len(dataset)

81

In [45]:
dataloader=DataLoader(dataset, batch_size=32, shuffle=True)
dataloader

In [46]:
for input,output in dataloader:
    print(input)
    print(output)
    

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0, 20, 45, 23],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 19, 20, 21, 22,  1,  2,
         23, 16, 24, 25],
        [ 0,  0,  0, 18, 19, 20, 21, 22,  1,  2, 23, 16, 24, 25, 10,  5,  7, 26,
         27, 19, 26, 28],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,
          3,  4,  5,  6],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 31, 32,  2, 33,  8,
         34, 35, 23,  5],
        [ 0,  0, 20, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37, 38, 39, 40, 41,
         29, 42, 41, 29],
        [ 0,  0,  0,  0,  0, 20, 45, 23, 46, 47,  8, 48, 49, 10, 50, 51,  2, 52,
         29, 53, 54, 29],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0, 18],
        [ 0,  0,  0,  0,  0,  0,  0, 

In [47]:
X.shape

torch.Size([81, 22])

In [48]:
len(dataset)

81

In [49]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

LSTM cell 

In [50]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(LSTMModel, self).__init__()
        self.embedding=nn.Embedding(vocab_size, embedding_dim)
        self.lstm=nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.fc=nn.Linear(hidden_dim, vocab_size)
    
    def forward(self,x):
        x=self.embedding(x)
        output,(h_n,c_n)=self.lstm(x)
        output=self.fc(output[:,-1,:])
        return output

In [78]:
model=LSTMModel(vocab_size=len(vocab), embedding_dim=50, hidden_dim=100)
model

LSTMModel(
  (embedding): Embedding(58, 50)
  (lstm): LSTM(50, 100, batch_first=True)
  (fc): Linear(in_features=100, out_features=58, bias=True)
)

In [79]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [80]:
model.to(device)

LSTMModel(
  (embedding): Embedding(58, 50)
  (lstm): LSTM(50, 100, batch_first=True)
  (fc): Linear(in_features=100, out_features=58, bias=True)
)

In [51]:
print(len(vocab))

58


In [52]:
X=nn.Embedding(284,100)
y=nn.LSTM(100,128,batch_first=True)
z=nn.Linear(128,284)

In [53]:
dataset[0][0].shape

torch.Size([22])

In [54]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 22])

In [55]:
a=dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [56]:
X(a)

tensor([[[ 0.1133,  0.5707, -1.1393,  ...,  1.4934,  0.8817,  0.0481],
         [ 0.1133,  0.5707, -1.1393,  ...,  1.4934,  0.8817,  0.0481],
         [ 0.1133,  0.5707, -1.1393,  ...,  1.4934,  0.8817,  0.0481],
         ...,
         [ 0.1133,  0.5707, -1.1393,  ...,  1.4934,  0.8817,  0.0481],
         [ 0.1133,  0.5707, -1.1393,  ...,  1.4934,  0.8817,  0.0481],
         [-0.7811, -0.6325, -0.5425,  ...,  0.9322, -0.4500,  0.2580]]],
       grad_fn=<EmbeddingBackward0>)

In [57]:
X(a).shape

torch.Size([1, 22, 100])

In [62]:
b=y(X(a))
b[0].shape

torch.Size([1, 22, 128])

In [63]:
c, d = b
c.shape, d[0].shape, d[1].shape

(torch.Size([1, 22, 128]), torch.Size([1, 1, 128]), torch.Size([1, 1, 128]))

In [64]:
len(d)

2

In [65]:
e, f=d

In [66]:
e.shape

torch.Size([1, 1, 128])

In [68]:
f.shape

torch.Size([1, 1, 128])

In [73]:
f_temp= f.squeeze(0).shape

In [70]:
f_temp=f.squeeze(0)

In [71]:
z(f_temp)

tensor([[ 0.2761, -0.2445,  0.1387,  0.2101,  0.3265,  0.0166, -0.0891, -0.0390,
         -0.0684,  0.0991, -0.1631, -0.0802, -0.0178,  0.1867,  0.0555, -0.2079,
          0.0613,  0.1460,  0.1994,  0.0407, -0.2097,  0.2513, -0.3210,  0.2299,
         -0.3493,  0.0184,  0.1583,  0.1898,  0.0876,  0.2411, -0.1100,  0.2776,
          0.0021,  0.2748,  0.2172,  0.4052, -0.2805, -0.2090, -0.2494,  0.1144,
          0.0554,  0.1984,  0.2297,  0.1354, -0.3402,  0.2348, -0.0191,  0.2706,
         -0.0787, -0.1132,  0.0720, -0.1901, -0.1377, -0.0865,  0.1812, -0.0530,
         -0.0854, -0.1870, -0.2368,  0.0797,  0.2220,  0.1000,  0.3150,  0.4304,
         -0.0012, -0.0390, -0.0065,  0.3446, -0.0514, -0.0399, -0.0492, -0.1715,
          0.1458,  0.1094,  0.1502, -0.1400,  0.6029,  0.0414,  0.1979, -0.6345,
         -0.5448, -0.4436, -0.3954,  0.1739,  0.0077,  0.1136,  0.1174,  0.2363,
          0.1668, -0.2361, -0.1712,  0.6089,  0.2259,  0.3010, -0.1260,  0.0020,
         -0.4456,  0.0240, -

In [72]:
(f_temp)

tensor([[-0.5547,  0.1281,  0.0837,  0.0387, -0.1120,  0.2069, -0.6285,  0.3775,
          0.4439,  0.1939, -0.0749, -0.6314, -0.3637, -0.1839, -0.2942, -0.5107,
          0.0127, -0.4444,  0.2504, -0.3232, -0.8339, -0.3760, -0.4958,  0.5166,
         -0.0172,  0.5697, -0.2744, -0.2724,  0.1304,  0.3039, -0.0541, -0.8136,
         -0.1655,  0.2813, -0.3533,  0.0990, -0.0267,  0.0581, -0.5695,  0.4689,
         -0.6216,  0.2297, -0.4863, -0.1316, -0.0844,  0.6732, -0.0653,  0.3999,
          0.2087,  0.4300,  0.3720,  0.1836, -0.0151,  0.9577, -0.4586,  0.2805,
          0.4990, -0.9909,  0.5953, -0.2527, -0.1092,  0.0178, -0.0983,  0.0063,
          0.3242,  0.1717, -0.1950, -0.0532, -0.2236,  0.4720,  0.1738,  0.2104,
         -0.2932,  0.2577, -0.3694, -0.0512, -0.5309,  0.6913,  0.2804, -0.6282,
         -0.0430, -0.2210, -1.0911,  0.0205,  0.1634, -0.1150,  0.2647, -0.2316,
         -0.0911, -0.4953, -0.2682,  0.5179, -0.0858, -0.2556, -0.2198,  0.3207,
         -0.1949,  0.1851,  

In [75]:
f_temp = f.squeeze(0)
len(f_temp[0])

128

In [76]:
len(vocab)

58

training loop 

In [88]:
for batch_x ,batch_y in dataloader:
    print(batch_x, batch_y)
    
    break

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 19, 20, 21, 22,  1,  2,
         23, 16, 24, 25],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
          2,  3,  4,  5],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0, 20],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
         11, 12, 13, 14],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 20, 45, 23, 46, 47,  8, 48, 49, 10, 50,
         51,  2, 52, 29],
        [ 0, 20, 31, 32,  2, 33,  8, 34, 35, 23,  5, 36, 37, 38, 39, 40, 41, 29,
         42, 41, 29, 43],
        [ 0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
         13, 14, 15, 16],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0, 20, 45],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,
          6,  7,  8,  9],
        [ 0,  0,  0,  0,  0,  0,  0, 

In [82]:
for params in model.parameters():
    print(params.shape)

torch.Size([58, 50])
torch.Size([400, 50])
torch.Size([400, 100])
torch.Size([400])
torch.Size([400])
torch.Size([58, 100])
torch.Size([58])


In [89]:
epochs=10
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(), lr=0.001)
learn_rate=0.001


In [90]:
for epoch in range(epochs):
    total_loss=0
    for batch_x ,batch_y in dataloader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        predictions = model(batch_x)
        loss = criterion(predictions, batch_y)
        loss.backward()
        optimizer.step()
        total_loss+=loss.item()
    print(f'Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(dataloader)}')

Epoch 1/10, Loss: 1.8444284598032634
Epoch 2/10, Loss: 1.7189938227335613
Epoch 3/10, Loss: 1.6258491277694702
Epoch 4/10, Loss: 1.5530173381169636
Epoch 5/10, Loss: 1.5124917030334473
Epoch 6/10, Loss: 1.4797569115956624
Epoch 7/10, Loss: 1.4213083187739055
Epoch 8/10, Loss: 1.3620369831720989
Epoch 9/10, Loss: 1.2889535029729207
Epoch 10/10, Loss: 1.2605570952097576


prediction 

In [91]:
document.split('\n')

['Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction ',
 'between computers and humans through natural language. The ultimate goal of NLP is to enable computers to understand, interpret, ',
 'and generate human language in a valuable way. NLP combines computational linguistics with machine learning, deep learning, statistical modeling, ',
 'and more. It has a wide range of applications including language translation, sentiment analysis, chatbots, and information retrieval.']

In [92]:
def prediction(model,vocab,text):
    tokenized_text=word_tokenize(text.lower())
    print(tokenized_text)

In [93]:
prediction(model,vocab,"the last train journey")


['the', 'last', 'train', 'journey']
