creating tensors 

In [1]:
import torch 
print(torch.__version__)

2.9.0+cpu


In [2]:
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is not available. Using CPU.


In [3]:
a=torch.empty(2,3)
a

tensor([[-1.0466e+34,  1.9562e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.9812, 0.4227, 0.7981],
        [0.8032, 0.8008, 0.2048]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1,2,3,4,5],[5,6,7,8,9]])

tensor([[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]])

In [10]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [11]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [13]:
x=torch.tensor( [[1,2,3],[4,5,6]] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [20]:
x.dtype

torch.int64

In [23]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [24]:
x.dtype

torch.int64

In [27]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [28]:
x.dtype

torch.int64

In [29]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [31]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [33]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [34]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [37]:
x=x*100
x

tensor([[100000, 200000, 300000],
        [400000, 500000, 600000]])

In [38]:
x//3

tensor([[ 33333,  66666, 100000],
        [133333, 166666, 200000]])

In [39]:
x**2

tensor([[ 10000000000,  40000000000,  90000000000],
        [160000000000, 250000000000, 360000000000]])

In [40]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

element wise operation

In [41]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [42]:
a

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [43]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [44]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [45]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [46]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [47]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [48]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [49]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [50]:
c=torch.tensor([-1,-2,-3,-4])

In [51]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [52]:
torch.neg(c)

tensor([1, 2, 3, 4])

In [53]:
d=torch.round(torch.tensor([2.5,3.5,1.7,4.6]))

In [54]:
d

tensor([2., 4., 2., 5.])

In [55]:
torch.ceil(d)

tensor([2., 4., 2., 5.])

In [57]:
torch.floor(d)

tensor([2., 4., 2., 5.])

In [60]:
torch.clamp(d,min=1,max=4)

tensor([2., 4., 2., 4.])

In [62]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [63]:
torch.mean(e)

tensor(4.6667)

In [64]:
torch.sum(e)

tensor(28.)

In [66]:
torch.sum(e,dim=1)

tensor([ 7., 21.])

In [67]:
torch.mean(e,dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [68]:
torch.median(e)

tensor(5.)

In [69]:
torch.max(e)

tensor(9.)

In [70]:
torch.min(e)

tensor(0.)

In [71]:
torch.prod(e)

tensor(0.)

In [72]:
torch.std(e)

tensor(3.8297)

In [73]:
torch.var(e)

tensor(14.6667)

In [74]:
#argmin ,argmax

torch.argmax(e)

tensor(3)

In [75]:
torch.argmin(e)

tensor(1)

matrix operations 

In [76]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [77]:
f

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [78]:
g=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [80]:
torch.matmul(f,g.T)

tensor([[132., 102.],
        [108.,  88.]])

In [81]:
#dot product 
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [82]:
torch.dot(vector1,vector2)

tensor(11)

In [83]:
f.shape

torch.Size([2, 3])

In [84]:
torch.transpose(f,0,1)

tensor([[3., 0.],
        [9., 5.],
        [4., 7.]])

In [86]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 6., 1.],
        [5., 5., 0.],
        [4., 3., 8.]])

In [87]:
torch.det(h)

tensor(-125.0000)

comparison operations 

In [88]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [89]:
i

tensor([[8., 3., 3.],
        [5., 0., 6.]])

In [90]:
j

tensor([[4., 0., 8.],
        [4., 7., 2.]])

In [91]:
i>j

tensor([[ True,  True, False],
        [ True, False,  True]])

In [92]:
# less than 
i < j

tensor([[False, False,  True],
        [False,  True, False]])

In [93]:
i == j 

tensor([[False, False, False],
        [False, False, False]])

In [94]:
i  != j 

tensor([[True, True, True],
        [True, True, True]])

special function 

In [3]:
k=torch.tensor([10,20,30])
k

tensor([10, 20, 30])

In [4]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [5]:
import torch 


torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [6]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [7]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [9]:
torch.softmax(k.float(), dim=0)

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

In [10]:
torch.relu(k)

tensor([10, 20, 30])

inplace operations 

In [11]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [13]:
b=a+5
b

tensor([6, 7, 8])

In [14]:
m =torch.rand(2,3)
n=torch.rand(2,3)

In [15]:
m

tensor([[0.1970, 0.5301, 0.2802],
        [0.2399, 0.1463, 0.6903]])

In [16]:
n

tensor([[0.3700, 0.7681, 0.8418],
        [0.7491, 0.7152, 0.2976]])

In [17]:
m.add(n)

tensor([[0.5670, 1.2982, 1.1220],
        [0.9890, 0.8615, 0.9879]])

In [18]:
torch.relu_(m)

tensor([[0.1970, 0.5301, 0.2802],
        [0.2399, 0.1463, 0.6903]])

In [20]:
m.relu_()

tensor([[0.1970, 0.5301, 0.2802],
        [0.2399, 0.1463, 0.6903]])

copying a tensor 

In [21]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [22]:
b=a 

In [23]:
b

[1, 2, 3, 4, 5]

In [24]:
b[2]=30

In [25]:
b

[1, 2, 30, 4, 5]

In [26]:
a

[1, 2, 30, 4, 5]

In [27]:
a=torch.tensor([1,2,3,4])
b=a.clone()

In [28]:
b

tensor([1, 2, 3, 4])

In [29]:
id(a)

1168001439360

weight updatation

In [30]:
import torch 
data=torch.tensor(
       [
              [2,3,4],
              [5,6,4],
              [7,8,5]
       ]
)
data


tensor([[2, 3, 4],
        [5, 6, 4],
        [7, 8, 5]])

In [33]:
x=data[:,0:2]
y=data[:,2]


In [34]:
x

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [35]:
y

tensor([4, 4, 5])

weight init

In [36]:
def initialize_parameters():
       parameters={}
       parameters['w1']=torch.ones((2,2))*0.1
       parameters['b1']=torch.zeros((2,1))*0.1

       parameters['w2']=torch.ones((2,1))*0.1
       parameters['b2']=torch.zeros((1,1))*0.1
       return parameters




In [37]:
initialize_parameters()

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

better way 

In [39]:
def initialize_parameters(layer_dims):
       torch.manual_seed(3)
       parameters={}
       L=len(layer_dims)
       for l in range(1,L):
              parameters['w'+str(l)]=torch.ones((layer_dims[l-1],layer_dims[l]))*0.1
              parameters['b'+str(l)]=torch.ones((layer_dims[l],1))*0.1
       return parameters
