creating tensors 

In [1]:
import torch 
print(torch.__version__)

2.9.0+cpu


In [6]:
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is not available. Using CPU.


In [7]:
a=torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
type(a)

torch.Tensor

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(2,3)

tensor([[0.2905, 0.6113, 0.1755],
        [0.0036, 0.7318, 0.4136]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.tensor([[1,2,3,4,5],[5,6,7,8,9]])

tensor([[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]])

In [15]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [17]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [19]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [21]:
x=torch.tensor( [[1,2,3],[4,5,6]] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape

torch.Size([2, 3])