creating tensors 

In [89]:
import torch 
print(torch.__version__)

2.9.0+cpu


In [90]:
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is not available. Using CPU.


In [91]:
a=torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [92]:
type(a)

torch.Tensor

In [93]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [94]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [95]:
torch.rand(2,3)

tensor([[0.6474, 0.4548, 0.1233],
        [0.7801, 0.4096, 0.7890]])

In [96]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [97]:
torch.tensor([[1,2,3,4,5],[5,6,7,8,9]])

tensor([[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]])

In [98]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [99]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [100]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [101]:
x=torch.tensor( [[1,2,3],[4,5,6]] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [102]:
x.shape

torch.Size([2, 3])

In [103]:
torch.empty_like(x)

tensor([[2551009446384,             0,             0],
        [            0,             0,             0]])

In [104]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [105]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [106]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [107]:
x.dtype

torch.int64

In [108]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [109]:
x.dtype

torch.int64

In [110]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [111]:
x.dtype

torch.int64

In [112]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [113]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [114]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [115]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [116]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [117]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [118]:
x=x*100
x

tensor([[100, 200, 300],
        [400, 500, 600]])

In [119]:
x//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [120]:
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [121]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

element wise operation

In [122]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [123]:
a

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [124]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [125]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [126]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [127]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [128]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [129]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [130]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [131]:
c=torch.tensor([-1,-2,-3,-4])

In [132]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [133]:
torch.neg(c)

tensor([1, 2, 3, 4])

In [134]:
d=torch.round(torch.tensor([2.5,3.5,1.7,4.6]))

In [135]:
d

tensor([2., 4., 2., 5.])

In [136]:
torch.ceil(d)

tensor([2., 4., 2., 5.])

In [137]:
torch.floor(d)

tensor([2., 4., 2., 5.])

In [138]:
torch.clamp(d,min=1,max=4)

tensor([2., 4., 2., 4.])

In [139]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [140]:
torch.mean(e)

tensor(4.5000)

In [141]:
torch.sum(e)

tensor(27.)

In [142]:
torch.sum(e,dim=1)

tensor([10., 17.])

In [143]:
torch.mean(e,dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [144]:
torch.median(e)

tensor(1.)

In [145]:
torch.max(e)

tensor(9.)

In [146]:
torch.min(e)

tensor(0.)

In [147]:
torch.prod(e)

tensor(0.)

In [148]:
torch.std(e)

tensor(4.5935)

In [149]:
torch.var(e)

tensor(21.1000)

In [150]:
#argmin ,argmax

torch.argmax(e)

tensor(2)

In [151]:
torch.argmin(e)

tensor(0)

matrix operations 

In [152]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [153]:
f

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [154]:
g=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [155]:
torch.matmul(f,g.T)

tensor([[ 21.,   0.],
        [100.,  74.]])

In [156]:
#dot product 
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [157]:
torch.dot(vector1,vector2)

tensor(11)

In [158]:
f.shape

torch.Size([2, 3])

In [159]:
torch.transpose(f,0,1)

tensor([[7., 9.],
        [0., 5.],
        [0., 7.]])

In [160]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]])

In [161]:
torch.det(h)

tensor(184.0000)

comparison operations 

In [162]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [163]:
i

tensor([[9., 2., 6.],
        [7., 7., 8.]])

In [164]:
j

tensor([[3., 6., 1.],
        [5., 5., 0.]])

In [165]:
i>j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [166]:
# less than 
i < j

tensor([[False,  True, False],
        [False, False, False]])

In [167]:
i == j 

tensor([[False, False, False],
        [False, False, False]])

In [168]:
i  != j 

tensor([[True, True, True],
        [True, True, True]])

special function 

In [169]:
k=torch.tensor([10,20,30])
k

tensor([10, 20, 30])

In [170]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [171]:
import torch 


torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [172]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [173]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [174]:
torch.softmax(k.float(), dim=0)

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

In [175]:
torch.relu(k)

tensor([10, 20, 30])

inplace operations 

In [176]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [177]:
b=a+5
b

tensor([6, 7, 8])

In [178]:
m =torch.rand(2,3)
n=torch.rand(2,3)

In [179]:
m

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [180]:
n

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [181]:
m.add(n)

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [182]:
torch.relu_(m)

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [183]:
m.relu_()

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

copying a tensor 

In [184]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [185]:
b=a 

In [186]:
b

[1, 2, 3, 4, 5]

In [187]:
b[2]=30

In [188]:
b

[1, 2, 30, 4, 5]

In [189]:
a

[1, 2, 30, 4, 5]

In [190]:
a=torch.tensor([1,2,3,4])
b=a.clone()

In [191]:
b

tensor([1, 2, 3, 4])

In [192]:
id(a)

2681937128544

weight updatation

In [193]:
import torch 
data=torch.tensor(
       [
              [2,3,4],
              [5,6,4],
              [7,8,5]
       ]
)
data


tensor([[2, 3, 4],
        [5, 6, 4],
        [7, 8, 5]])

In [194]:
x=data[:,0:2]
y=data[:,2]


In [195]:
x

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [196]:
y

tensor([4, 4, 5])

weight init

In [197]:
def initialize_parameters():
       parameters={}
       parameters['w1']=torch.ones((2,2))*0.1
       parameters['b1']=torch.zeros((2,1))*0.1

       parameters['w2']=torch.ones((2,1))*0.1
       parameters['b2']=torch.zeros((1,1))*0.1
       return parameters




In [198]:
initialize_parameters()

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

better way 

In [199]:
def initialize_parameters(layer_dims):
       torch.manual_seed(3)
       parameters={}
       L=len(layer_dims)
       for l in range(1,L):
              parameters['w'+str(l)]=torch.ones((layer_dims[l-1],layer_dims[l]))*0.1
              parameters['b'+str(l)]=torch.ones((layer_dims[l],1))*0.1
       return parameters


forward propagation

In [200]:
def linear_forward(A_prev,w,b):
       z=torch.matmul(w.T,A_prev)+b
       return z

In [201]:
initialize_parameters([2,2,1])

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.1000],
         [0.1000]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.1000]])}

In [202]:
def L_layer_forward(x,parameters):
       A=x
       L=len(parameters)//2

       for l in range(1,L+1):
              A_prev=A 
              wl=parameters['w'+str(l)]
              bl=parameters['b'+str(l)]
              A=linear_forward(A_prev,wl,bl)
              return A,A_prev

In [203]:
x

tensor([[2, 3],
        [5, 6],
        [7, 8]])

In [204]:
params=initialize_parameters([2,2,1])
params

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.1000],
         [0.1000]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.1000]])}

In [205]:
x_sample=x[0].reshape(2,1)
x_sample

tensor([[2],
        [3]])

In [206]:
y_hat,A1=L_layer_forward(x_sample.float(),params)

In [207]:
print(y_hat)

tensor([[0.6000],
        [0.6000]])


In [208]:
A1

tensor([[2.],
        [3.]])

In [209]:
(y-y_hat)**2

tensor([[11.5600, 11.5600, 19.3600],
        [11.5600, 11.5600, 19.3600]])

In [210]:
params

{'w1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.1000],
         [0.1000]]),
 'w2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.1000]])}

In [211]:
params['w2'][1,0]

tensor(0.1000)

In [212]:
A1

tensor([[2.],
        [3.]])

In [213]:
import torch 

In [214]:
x=torch.tensor(1.0,requires_grad=True)

In [215]:
x

tensor(1., requires_grad=True)

In [216]:
y=x**2
y

tensor(1., grad_fn=<PowBackward0>)

In [217]:
y=x**2
y.backward()
x.grad

tensor(2.)

In [218]:
def nested_fun(x):
       return 2*x*torch.cos(x**2)

In [219]:
import torch
a=torch.tensor([3])
a

tensor([3])

second function 

In [220]:
x=torch.tensor(2.0,requires_grad=True)


In [221]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [222]:
z=torch.sin(y)
z

tensor(-0.7568, grad_fn=<SinBackward0>)

In [223]:
z.backward()

In [224]:
x.grad

tensor(-2.6146)

In [225]:
# bce loss 

In [226]:
def bce_loss(y_hat,y):
       loss=-(y*torch.log(y_hat)+(1-y)*torch.log(1-y_hat))
       return loss

In [227]:
x=torch.tensor(2)
y=torch.tensor(0)

In [228]:
w=torch.tensor(1)
b=torch.tensor(0)

In [229]:
def bce(y_hat,y):
       y_hat=torch.clamp(y_hat,1e-7,1-1e-7)
       loss=-(y*torch.log(y_hat)+(1-y)*torch.log(1-y_hat))
       return loss

In [230]:
z=w*x+b 
y_pred=torch.sigmoid(z)
loss=bce_loss(y_pred,y)

In [231]:
loss

tensor(2.1269)

In [232]:
#derivatives 

In [233]:
loss_dy_pred=(y_pred-y)/(y_pred*(1-y_pred))
dy_pred_dz=y_pred*(1-y_pred)
dz_dw=x
dz_db=1


In [234]:
dl_dw=loss_dy_pred*dy_pred_dz*dz_dw
dl_db=loss_dy_pred*dy_pred_dz*dz_db

In [235]:
dl_dw
dl_db

tensor(0.8808)

In [236]:
dl_dw

tensor(1.7616)

In [237]:
#using autograd

In [238]:
x=torch.tensor(2)
y=torch.tensor(0)

In [239]:
w=torch.tensor(1.0 ,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [240]:
z=w*x+b

In [241]:
z

tensor(2., grad_fn=<AddBackward0>)

In [242]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.8808, grad_fn=<SigmoidBackward0>)

In [243]:
loss=bce(y_pred,y)
loss.backward()

In [244]:
loss

tensor(2.1269, grad_fn=<NegBackward0>)

In [245]:
print(w.grad)

tensor(1.7616)


In [246]:
print(b.grad)

tensor(0.8808)


In [247]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [248]:
x

tensor([1., 2., 3.], requires_grad=True)

In [249]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [250]:
y.backward()

In [251]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

clearing grad 

In [252]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [253]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [254]:
y.backward()

In [255]:
x.grad

tensor(4.)

In [256]:
#option 1 

In [257]:
x.grad.zero_()

tensor(0.)

In [258]:
# option  2 
x.requires_grad_(False)

tensor(2.)

In [259]:
x

tensor(2.)

In [260]:
y=(x**2).mean()
y

tensor(4.)

In [261]:
y

tensor(4.)

In [262]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [263]:
# some times error asha tai santi

detach

In [264]:
x=torch.tensor(2.0,requires_grad=True)

In [266]:
z=x.detach()

In [267]:
z

tensor(2.)

In [268]:
x

tensor(2., requires_grad=True)

In [269]:
y=x**2

In [270]:
y

tensor(4., grad_fn=<PowBackward0>)

In [271]:
y1=z**2

In [272]:
y1

tensor(4.)

In [273]:
y.backward()

In [274]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn