In [2]:
import torch 
import torch.nn as nn

In [3]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()

              self.linear=nn.Linear(num_features,1)
              self.sigmoid=nn.Sigmoid()
       def forward(self,features):
              out=self.linear(features)
              out=self.sigmoid(out)
              return out



version 2 

In [13]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()

              self.linear1=nn.Linear(num_features,3)
              self.relu=nn.ReLU()
              #linear layer 2 
              self.linear2=nn.Linear(3,1)
              self.sigmoid=nn.Sigmoid()
       def forward(self,features):
              out=self.linear1(features)
              
              out=self.relu(out)
              out=self.linear2(out)
              out=self.sigmoid(out)
              return out

version 3 

In [25]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()
              self.network=nn.Sequential(
                     nn.Linear(num_features,3),
                     nn.ReLU(),
                     nn.Linear(3,1),
                     nn.Sigmoid()
              )

             
       def forward(self,features):
              out=self.network(features)
              return out

Torch info 

In [26]:
#create dataset 
features=torch.rand(10,5)

In [27]:
features

tensor([[0.2682, 0.8738, 0.4649, 0.7774, 0.5390],
        [0.8392, 0.7801, 0.5041, 0.5538, 0.2149],
        [0.7506, 0.6563, 0.0468, 0.0265, 0.6142],
        [0.6947, 0.7803, 0.3551, 0.2791, 0.2633],
        [0.8712, 0.2947, 0.5797, 0.6629, 0.0747],
        [0.6942, 0.3380, 0.0984, 0.1325, 0.5280],
        [0.8576, 0.4672, 0.9095, 0.5226, 0.6670],
        [0.9331, 0.9003, 0.2366, 0.0539, 0.9312],
        [0.4605, 0.3261, 0.0566, 0.0831, 0.6649],
        [0.1232, 0.2928, 0.6726, 0.0232, 0.2439]])

In [28]:
features.shape[1]

5

In [29]:
model=Model(features.shape[1])

In [30]:
#calling for forward pass 
model(features)

tensor([[0.5790],
        [0.5919],
        [0.5818],
        [0.5922],
        [0.6064],
        [0.5880],
        [0.6105],
        [0.5810],
        [0.5862],
        [0.6232]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight 

AttributeError: 'Model' object has no attribute 'linear'

In [22]:
model.linear2.weight

Parameter containing:
tensor([[-0.1611,  0.0236,  0.5507]], requires_grad=True)

In [18]:
! pip install torchinfo

In [34]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

complex model 

In [38]:
model.network[0].weight

Parameter containing:
tensor([[ 0.3373, -0.2700, -0.1410,  0.0688, -0.2278],
        [-0.0179, -0.1486,  0.4108, -0.2421, -0.1224],
        [ 0.1943, -0.2496, -0.0529,  0.3449, -0.3623]], requires_grad=True)