In [2]:
import torch 
import torch.nn as nn

In [3]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()

              self.linear=nn.Linear(num_features,1)
              self.sigmoid=nn.Sigmoid()
       def forward(self,features):
              out=self.linear(features)
              out=self.sigmoid(out)
              return out



version 2 

In [13]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()

              self.linear1=nn.Linear(num_features,3)
              self.relu=nn.ReLU()
              #linear layer 2 
              self.linear2=nn.Linear(3,1)
              self.sigmoid=nn.Sigmoid()
       def forward(self,features):
              out=self.linear1(features)
              
              out=self.relu(out)
              out=self.linear2(out)
              out=self.sigmoid(out)
              return out

Torch info 

In [14]:
#create dataset 
features=torch.rand(10,5)

In [15]:
features

tensor([[0.6547, 0.0788, 0.2356, 0.8825, 0.7002],
        [0.1124, 0.6325, 0.4754, 0.6274, 0.4216],
        [0.7811, 0.4120, 0.8671, 0.9618, 0.4675],
        [0.2921, 0.6345, 0.1401, 0.4875, 0.4936],
        [0.8037, 0.0656, 0.8312, 0.6762, 0.1898],
        [0.9054, 0.2550, 0.7312, 0.8921, 0.2207],
        [0.0814, 0.6918, 0.4695, 0.9362, 0.3973],
        [0.9766, 0.9124, 0.2632, 0.7365, 0.8241],
        [0.4090, 0.2489, 0.0301, 0.8209, 0.7763],
        [0.0497, 0.4678, 0.7607, 0.2833, 0.8890]])

In [16]:
features.shape[1]

5

In [17]:
model=Model(features.shape[1])

In [18]:
#calling for forward pass 
model(features)

tensor([[0.4787],
        [0.5199],
        [0.4821],
        [0.5220],
        [0.4848],
        [0.4848],
        [0.5151],
        [0.5044],
        [0.4832],
        [0.5122]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear1.weight 

Parameter containing:
tensor([[ 0.0709, -0.0137, -0.0008,  0.0177,  0.3874],
        [-0.0570,  0.2817, -0.2256, -0.1221,  0.3393],
        [-0.1781,  0.3972, -0.0701, -0.2124, -0.0214]], requires_grad=True)

In [22]:
model.linear2.weight

Parameter containing:
tensor([[-0.1611,  0.0236,  0.5507]], requires_grad=True)

In [18]:
! pip install torchinfo

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

complex model 