In [2]:
import torch 
import torch.nn as nn

In [3]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()

              self.linear=nn.Linear(num_features,1)
              self.sigmoid=nn.Sigmoid()
       def forward(self,features):
              out=self.linear(features)
              out=self.sigmoid(out)
              return out



version 2 

In [11]:
class Model(nn.Module):
       def __init__ (self,num_features):
              super().__init__()

              self.linear1=nn.Linear(num_features,3)
              self.relu=nn.ReLU()
              #linear layer 2 
              self.linear2=nn.Linear(3,1)
              self.sigmoid=nn.Sigmoid()
       def forward(self,features):
              out=self.linear1(features)
              out=self.relu(out)
              out=self.sigmoid(out)
              return out

Torch info 

In [4]:
#create dataset 
features=torch.rand(10,5)

In [5]:
features

tensor([[0.8397, 0.4808, 0.0228, 0.9632, 0.9739],
        [0.5310, 0.8897, 0.5913, 0.3672, 0.7664],
        [0.9118, 0.3070, 0.7480, 0.7701, 0.3166],
        [0.3924, 0.0658, 0.8969, 0.7490, 0.8584],
        [0.4247, 0.9072, 0.5905, 0.1148, 0.5999],
        [0.5132, 0.9912, 0.7825, 0.8585, 0.6386],
        [0.2463, 0.7949, 0.3551, 0.8739, 0.2015],
        [0.1955, 0.4260, 0.0292, 0.8609, 0.9425],
        [0.9626, 0.8760, 0.7791, 0.6434, 0.7174],
        [0.1953, 0.5359, 0.1345, 0.7476, 0.5780]])

In [6]:
features.shape[1]

5

In [7]:
model=Model(features.shape[1])

In [8]:
#calling for forward pass 
model(features)

tensor([[0.5620],
        [0.5752],
        [0.5020],
        [0.4587],
        [0.5671],
        [0.5535],
        [0.4897],
        [0.4984],
        [0.5954],
        [0.4900]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.weight 

Parameter containing:
tensor([[ 0.3726,  0.4288, -0.0868, -0.1575,  0.2451]], requires_grad=True)

In [18]:
! pip install torchinfo

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

complex model 